PRINT "        Playing Coffin Dance..."
PRINT
PRINT "         ======================"
PRINT "        /                    /|"
PRINT "       ====================== /"
PRINT "       |                    |/"
PRINT "       =================="
PRINT "         \M\  \M/  \M/  \M\"
PRINT "          A    A    A    A"
PRINT "         ¾ Ô  ¾ Ô  ¾ Ô  ¾ Ô"

PLAY "t124 o3"
PLAY "l4 g l8 g>dc p8 <b- p8 l4 a l8 aa l4 >c l8 <b-a l4 g p8 l8 >b-ab-ab- l4 <g p8 l8 >b-ab-ab-"
PLAY "l4 <g l8 g>dc p8 <b- p8 l4 a l8 aa l4 >c l8 <b-a l4 g p8 l8 >b-ab-ab- l4 <g p8 l8 >b-ab-ab-"
PLAY "l4 <g l8 g>dc p8 <b- p8 l4 a l8 aa l4 >c l8 <b-a l4 g p8 l8 >b-ab-ab- l4 <g p8 l8 >b-ab-ab-"
PLAY "<b-b-b-b->ddddccccffffggggggggggggdc<b-f"
PLAY "l4 g l8 g>dc p8 <b- p8 l4 a l8 aa l4 >c l8 <b-a l4 g p8 l8 >b-ab-ab- l4 <g p8 l8 >b-ab-ab-"
PLAY "l4 <g l8 g>dc p8 <b- p8 l4 a l8 aa l4 >c l8 <b-a l4 g p8 l8 >b-ab-ab- l4 <g p8 l8 >b-ab-ab-"
PLAY "l4 <g l8 g>dc p8 <b- p8 l4 a l8 aa l4 >c l8 <b-a l4 g p8 l8 >b-ab-ab- l4 <g p8 l8 >b-ab-ab-"
PLAY "<b-b-b-b->ddddccccffffggggggggggggdc<b-f l4 g"

